import React from 'react'

const FooterAbout = () => {
  return (
    <div className='footer-about'>
        <h2>About AYARHEP</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In totam labore fuga mollitia, facilis praesentium minima provident, cupiditate vel officia magni a voluptates? Fugiat rem nam doloremque quaerat, aspernatur impedit, debitis error a eveniet tenetur facilis numquam itaque corporis laborum recusandae quod accusantium magni nihil repellendus et voluptatum cupiditate exercitationem doloribus eligendi. Velit illo, ea architecto voluptates veritatis dolores temporibus optio autem excepturi inventore repudiandae reiciendis distinctio sunt eius vitae, maxime cumque reprehenderit quae corrupti repellat ullam. Possimus dolorem quos excepturi atque odio ipsum necessitatibus corporis rem quia in molestiae corrupti deserunt nam magni nisi neque libero, omnis et molestias!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In totam labore fuga mollitia, facilis praesentium minima provident, cupiditate vel officia magni a voluptates? Fugiat rem nam doloremque quaerat, aspernatur impedit, debitis error a eveniet tenetur facilis numquam itaque corporis laborum recusandae quod accusantium magni nihil repellendus et voluptatum cupiditate exercitationem doloribus eligendi. Velit illo, ea architecto voluptates veritatis dolores temporibus optio autem excepturi inventore repudiandae reiciendis distinctio sunt eius vitae, maxime cumque reprehenderit quae corrupti repellat ullam. Possimus dolorem quos excepturi atque odio ipsum necessitatibus corporis rem quia in molestiae corrupti deserunt nam magni nisi neque libero, omnis et molestias!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In totam labore fuga mollitia, facilis praesentium minima provident, cupiditate vel officia magni a voluptates? Fugiat rem nam doloremque quaerat, aspernatur impedit, debitis error a eveniet tenetur facilis numquam itaque corporis laborum recusandae quod accusantium magni nihil repellendus et voluptatum cupiditate exercitationem doloribus eligendi. Velit illo, ea architecto voluptates veritatis dolores temporibus optio autem excepturi inventore repudiandae reiciendis distinctio sunt eius vitae, maxime cumque reprehenderit quae corrupti repellat ullam. Possimus dolorem quos excepturi atque odio ipsum necessitatibus corporis rem quia in molestiae corrupti deserunt nam magni nisi neque libero, omnis et molestias!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In totam labore fuga mollitia, facilis praesentium minima provident, cupiditate vel officia magni a voluptates? Fugiat rem nam doloremque quaerat, aspernatur impedit, debitis error a eveniet tenetur facilis numquam itaque corporis laborum recusandae quod accusantium magni nihil repellendus et voluptatum cupiditate exercitationem doloribus eligendi. Velit illo, ea architecto voluptates veritatis dolores temporibus optio autem excepturi inventore repudiandae reiciendis distinctio sunt eius vitae, maxime cumque reprehenderit quae corrupti repellat ullam. Possimus dolorem quos excepturi atque odio ipsum necessitatibus corporis rem quia in molestiae corrupti deserunt nam magni nisi neque libero, omnis et molestias!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In totam labore fuga mollitia, facilis praesentium minima provident, cupiditate vel officia magni a voluptates? Fugiat rem nam doloremque quaerat, aspernatur impedit, debitis error a eveniet tenetur facilis numquam itaque corporis laborum recusandae quod accusantium magni nihil repellendus et voluptatum cupiditate exercitationem doloribus eligendi. Velit illo, ea architecto voluptates veritatis dolores temporibus optio autem excepturi inventore repudiandae reiciendis distinctio sunt eius vitae, maxime cumque reprehenderit quae corrupti repellat ullam. Possimus dolorem quos excepturi atque odio ipsum necessitatibus corporis rem quia in molestiae corrupti deserunt nam magni nisi neque libero, omnis et molestias!</p>
    </div>
  )
}

export default FooterAbout
